encryption_algorithms: [
  'aes128-ctr',
  'aes192-ctr',
  'aes256-ctr',
  'AEAD_AES_128_GCM',
  'AEAD_AES_256_GCM',
  'chacha20-poly1305'
]
kex_algorithms: [
  'curve25519-sha256',
  'diffie-hellman-group-exchange-sha256',
  'diffie-hellman-group14-sha256',
  'diffie-hellman-group15-sha512',
  'diffie-hellman-group16-sha512',
  'diffie-hellman-group18-sha512',
  'ecdh-sha2-nistp256',
  'ecdh-sha2-nistp384',
  'ecdh-sha2-nistp521',
  'kex-strict-s-v00',
  'sntrup761x25519-sha512'
]
mac_algorithms: [
  'hmac-sha2-256',
  'hmac-sha2-512',
  'hmac-sha2-256-etm',
  'hmac-sha2-512-etm'
]
server_host_key_algorithms: [
  'ecdsa-sha2-nistp256',
  'ecdsa-sha2-nistp384',
  'ecdsa-sha2-nistp521',
  'pgp-sign-dss',
  'x509v3-ecdsa-sha2-nistp256',
  'x509v3-ecdsa-sha2-nistp384',
  'x509v3-ecdsa-sha2-nistp521'
]
